# Generated by Django 3.2.16 on 2024-01-12 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_follow_uq_user_following'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='uq_user_following',
        ),
    ]
