# Generated by Django 3.2.16 on 2024-01-15 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_follow_uq_user_following'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['pub_date']},
        ),
    ]
